In [5]:
#MANAS TIWARI 2023UG1031

#importing numpy and pandas
import pandas as pd
import numpy as np

#reading AQI_data.csv
df = pd.read_csv('AQI_Data.csv')
data = np.array(df)

# (a) - Display the first 5 rows
print('First 5 rows of the dataset :-')
print(df.head(5))

#(b) - Display the last 6 rows
print('\nLast 6 rows the dataset :-')
print(df.tail(6))

#(c) - Show the summary statistics of the dataset
print('\nSummary of the dataset :-')
print(df.describe())

#(d) - Compute the mean AQI of each city of the dataset
AQI = df.groupby('City')['AQI'].apply(lambda x: np.mean(x.to_numpy()))
PM10 = df.groupby('City')['PM10'].apply(lambda x: np.mean(x.to_numpy()))
PM25 = df.groupby('City')['PM2.5'].apply(lambda x: np.mean(x.to_numpy()))

print('\nMean AQI of each city :-')
print(AQI)
print('\nMean PM2.5 of each city :-')
print(PM25)
print('\nMean PM10 of each city :-')
print(PM10)

#Set - 3
PM25_morethen_100 = df['PM2.5']>100
row_list = df[PM25_morethen_100]  # filtered data
print("\nRows having PM2.5 more than 100 :-")
print(row_list)

row_count = {}      # dictionary to store count of each city
for i in row_list['City']:
    if i in row_count:
        row_count[i] += 1
    else:
        row_count[i] = 1   
        
print("\nCount of rows having PM2.5 more than 100 in each city :-")
for i,j in  row_count.items():
    print(f"{i} = {j}")

First 5 rows of the dataset :-
    City        Date  AQI  PM2.5  PM10        NO2        CO          O3  \
0  Delhi  2024-01-01  152    153   151  26.509131  1.581413  123.401530
1  Delhi  2024-01-02  264    288   268  87.955853  1.242119  144.533790
2  Delhi  2024-01-03  307    344   357  94.469744  0.101480  198.520196
3  Delhi  2024-01-04  363    334   347  12.075618  1.097072   85.973585
4  Delhi  2024-01-05  237    266   250  51.046299  1.591834   47.938019

         SO2
0  25.062474
1   5.926302
2  32.786668
3   7.099955
4  28.140550

Last 6 rows the dataset :-
      City        Date  AQI  PM2.5  PM10        NO2        CO          O3  \
2556  Pune  2024-12-26   80     95    82  88.809636  0.497454  129.043801
2557  Pune  2024-12-27  419    448   462  26.701714  1.553582   86.973954
2558  Pune  2024-12-28  252    202   182  19.920962  1.599821   41.939484
2559  Pune  2024-12-29  365    414   410  80.815702  1.919950   39.982167
2560  Pune  2024-12-30  253    269   285  66.231614  0.611800   63.966705
2561  Pune  2024-12-31   95    140   117  99.505459  0.122817  112.774765

            SO2
2556   8.657624
2557  44.263423
2558  20.545087
2559  22.646297
2560  10.580135
2561  30.814997

Summary of the dataset :-
               AQI        PM2.5         PM10          NO2           CO  \
count  2562.000000  2562.000000  2562.000000  2562.000000  2562.000000
mean    277.635051   276.738486   275.988290    54.151115     1.037476
std     128.603738   131.015126   131.900856    25.744072     0.560294
min      50.000000     2.000000   -26.000000    10.036926     0.100100
25%     166.250000   165.000000   166.000000    32.025372     0.545341
50%     276.000000   274.500000   274.000000    53.606459     1.010095
75%     388.750000   388.000000   386.000000    76.322683     1.533300
max     499.000000   543.000000   559.000000    99.974242     1.999528

                O3          SO2
count  2562.000000  2562.000000
mean    104.832673    27.746349
std      54.878784    12.927527
min      10.045129     5.000524
25%      58.169877    16.685076
50%     104.345545    27.872017
75%     152.515574    38.878445
max     199.979607    49.976055

Mean AQI of each city :-
City
Bangalore    279.543716
Chennai      274.314208
Delhi        279.153005
Hyderabad    280.355191
Kolkata      265.901639
Mumbai       287.797814
Pune         276.379781
Name: AQI, dtype: float64

Mean PM2.5 of each city :-
City
Bangalore    278.469945
Chennai      275.139344
Delhi        279.898907
Hyderabad    277.825137
Kolkata      264.663934
Mumbai       286.046448
Pune         275.125683
Name: PM2.5, dtype: float64

Mean PM10 of each city :-
City
Bangalore    277.759563
Chennai      273.265027
Delhi        279.349727
Hyderabad    276.456284
Kolkata      263.644809
Mumbai       286.669399
Pune         274.773224
Name: PM10, dtype: float64

Rows having PM2.5 more than 100 :-
       City        Date  AQI  PM2.5  PM10        NO2        CO          O3  \
0     Delhi  2024-01-01  152    153   151  26.509131  1.581413  123.401530
1     Delhi  2024-01-02  264    288   268  87.955853  1.242119  144.533790
2     Delhi  2024-01-03  307    344   357  94.469744  0.101480  198.520196
3     Delhi  2024-01-04  363    334   347  12.075618  1.097072   85.973585
4     Delhi  2024-01-05  237    266   250  51.046299  1.591834   47.938019
...     ...         ...  ...    ...   ...        ...       ...         ...
2557   Pune  2024-12-27  419    448   462  26.701714  1.553582   86.973954
2558   Pune  2024-12-28  252    202   182  19.920962  1.599821   41.939484
2559   Pune  2024-12-29  365    414   410  80.815702  1.919950   39.982167
2560   Pune  2024-12-30  253    269   285  66.231614  0.611800   63.966705
2561   Pune  2024-12-31   95    140   117  99.505459  0.122817  112.774765

            SO2
0     25.062474
1      5.926302
2     32.786668
3      7.099955
4     28.140550
...         ...
2557  44.263423
2558  20.545087
2559  22.646297
2560  10.580135
2561  30.814997

[2290 rows x 9 columns]

Count of rows having PM2.5 more than 100 in each city :-
Delhi = 331
Mumbai = 335
Kolkata = 325
Chennai = 329
Bangalore = 322
Hyderabad = 321
Pune = 327